In [2]:
%matplotlib inline

from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pylab as plt
from sklearn.model_selection import train_test_split

In [8]:
housing_data=pd.read_csv('03_BostonHousing.csv')
#rename Cat.MEDV for easier data handling 
housing_data.rename(columns={'CAT. MEDV': 'CAT_MEDV'}, inplace=True)

In [10]:
housing_data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,LSTAT,MEDV,CAT_MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,4.98,24.0,0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,9.14,21.6,0
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,4.03,34.7,1
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,2.94,33.4,1
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,5.33,36.2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,9.67,22.4,0
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,9.08,20.6,0
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,5.64,23.9,0
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,6.48,22.0,0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,7.88,11.9,0

In [11]:
#The goal is to predict the median house price in new tracts based on information such as crime rate, pollution, and number of rooms.

In [13]:
# Question 1 Answer = Test sets allow the predictor model to run predictions on unseen data avoiding overfitting and setting a benchmark to evaluate the model, while training sets are used to teach the model. This allows the model to run predictions on seen data. With both training and test sets one is able to get a sense of the prediction model's performance/reliability.

In [34]:
from sklearn.linear_model import LinearRegression

# Select predictors and target variable
X = housing_data[['CRIM', 'CHAS', 'RM']]  # Predictors
y = housing_data['MEDV']  # Target variable

# Fit the multiple Linear Regression model
model = LinearRegression()
model= model.fit(X, y)

# Get coefficients and intercept
intercept = model.intercept_
coefficients = model.coef_

In [35]:
# Step 5: Print the regression equation
print(f"Regression Equation: MEDV = {intercept:.2f} + {coefficients[0]:.2f}*CRIM + {coefficients[1]:.2f}*CHAS + {coefficients[2]:.2f}*RM")

Regression Equation: MEDV = -28.81 + -0.26*CRIM + 3.76*CHAS + 8.28*RM

In [36]:
#MEDV? when CRIM = 0.1, CHAS = 0, RM = 6
#Question 3 Answer = The predicted median house price MEDV is approximately 20.84 or $20,840 after plugging given values into the regression equation